'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAddress
    Public Property fldAddressID As Integer
    Public Property fldAddress As String
    Public Property fldPostCode As String
    Public Property fldCountryID As Nullable(Of Integer)
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldAddress1 As String
    Public Property fldCity As String
    Public Property fldCounty As String
    Public Property fldLatitude As Nullable(Of Double)
    Public Property fldLongitude As Nullable(Of Double)

End Class
