'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSTrafficLight
    Public Property fldTrafficLightID As Integer
    Public Property fldProjectID As Nullable(Of Integer)
    Public Property fldTypeID As Nullable(Of Integer)
    Public Property fldDescription As String
    Public Property fldQBColorValue As Nullable(Of Integer)
    Public Property fldSourceID As Nullable(Of Integer)

End Class
