'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSChangeType
    Public Property fldChangeTypeID As Integer
    Public Property fldProductProjectID As Nullable(Of Integer)
    Public Property fldChangeCode As String
    Public Property fldChangeDescription As String
    Public Property fldFromBucketString As String
    Public Property fldToBucketString As String
    Public Property fldPredefinedYesNo As Nullable(Of Boolean)
    Public Property fldFullDescription As String
    Public Property fldRecordStatus As String
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldChangeCommentary As String

End Class
