'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSValuation
    Public Property fldValuationID As Integer
    Public Property fldValuationGroupID As Nullable(Of Integer)
    Public Property fldPackageID As Nullable(Of Integer)
    Public Property fldGrossCertifiedValue As Nullable(Of Double)
    Public Property fldPercentofEFC As Nullable(Of Double)
    Public Property fldRetained As Nullable(Of Double)
    Public Property fldWithheld As Nullable(Of Double)
    Public Property fldTotalNet As Nullable(Of Double)
    Public Property fldRecordStatus As String
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldProductProjectID As Integer
    Public Property fldRetainedPercent As Nullable(Of Double)
    Public Property fldValueOffSite As Nullable(Of Double)
    Public Property fldGrossToDate As Nullable(Of Double)

End Class
