'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMGroupsFormOptionalHeader
    Public Property fldProductProjectID As Integer
    Public Property fldGrpRef1 As String
    Public Property fldGrpRef1Hidden As Boolean
    Public Property fldGrpRef2 As String
    Public Property fldGrpRef2Hidden As Boolean
    Public Property fldGrpRef3 As String
    Public Property fldGrpRef3Hidden As Boolean
    Public Property fldGrpName1 As String
    Public Property fldGrpName1Hidden As Boolean
    Public Property fldGrpName2 As String
    Public Property fldGrpName2Hidden As Boolean
    Public Property fldGrpParentCode As String
    Public Property fldGrpParentCodeHidden As Boolean
    Public Property fldGrpParentLabel As String
    Public Property fldGrpParentLabelHidden As Boolean

End Class
