'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSContractReportingPeriod
    Public Property fldPeriodID As Integer
    Public Property fldGroupPackageID As Nullable(Of Integer)
    Public Property fldRowOrderID As Nullable(Of Integer)
    Public Property fldPeriodDescription As String
    Public Property fldPlannedPeriodStartDate As Nullable(Of Date)
    Public Property fldPlannedPeriodCompletionDate As Nullable(Of Date)
    Public Property fldActualPeriodStartDate As Nullable(Of Date)
    Public Property fldActualPeriodCompletionDate As Nullable(Of Date)
    Public Property fldFirstChangeNumber As String
    Public Property fldDateofChange As Nullable(Of Date)
    Public Property fldRecordStatus As String
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldProductProjectID As Integer
    Public Property fldReportDate As Nullable(Of Date)
    Public Property fldReportNumber As String
    Public Property fldContractID As Nullable(Of Short)

End Class
