'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSReportPeriod
    Public Property fldPeriodID As Integer
    Public Property fldGroupPackageID As Nullable(Of Integer)
    Public Property fldCurrentReportingPeriod As Nullable(Of Integer)
    Public Property fldDateofChange As Nullable(Of Date)
    Public Property fldSourceID As Nullable(Of Integer)

End Class
