'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSProjectReportExclusion
    Public Property fldExclusionID As Integer
    Public Property fldProjectID As Nullable(Of Integer)
    Public Property fldOrderinProject As Nullable(Of Integer)
    Public Property fldExclusionMemo As String
    Public Property fldRecordStatus As String
    Public Property fldSourceID As Nullable(Of Integer)

End Class
