'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMPackagesFormOptionalHeader
    Public Property fldProductProjectID As Integer
    Public Property fldPackRef1 As String
    Public Property fldPackRef1Hidden As Boolean
    Public Property fldPackRef2 As String
    Public Property fldPackRef2Hidden As Boolean
    Public Property fldPackRef3 As String
    Public Property fldPackRef3Hidden As Boolean
    Public Property fldPackName1 As String
    Public Property fldPackName1Hidden As Boolean
    Public Property fldPackName2 As String
    Public Property fldPackName2Hidden As Boolean
    Public Property fldPackName3 As String
    Public Property fldPackName3Hidden As Boolean
    Public Property fldPackName4 As String
    Public Property fldPackName4Hidden As Boolean
    Public Property fldPackName5 As String
    Public Property fldPackName5Hidden As Boolean
    Public Property fldPackName6 As String
    Public Property fldPackName6Hidden As Boolean

End Class
