'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSGroupPackage
    Public Property fldGroupPackageID As Integer
    Public Property fldProductProjectID As Nullable(Of Integer)
    Public Property fldContractID As Nullable(Of Integer)
    Public Property fldGroupPackageName As String
    Public Property fldGroupPackageDescription As String
    Public Property fldPreDefinedYesNo As Nullable(Of Boolean)
    Public Property fldInitialBudgetDate As Nullable(Of Date)
    Public Property fldGrossInterimValuationDate As Nullable(Of Date)
    Public Property fldContractCommencementDate As Nullable(Of Date)
    Public Property fldContractCompletionDate As Nullable(Of Date)
    Public Property fldExtendedContractCompletionDate As Nullable(Of Date)
    Public Property fldContractBudget As Nullable(Of Double)
    Public Property fldContractVAT As Nullable(Of Double)
    Public Property fldContractNotes As String
    Public Property fldPreviousAdvanceWarnings As Nullable(Of Double)
    Public Property fldPreviousUnapprovedEstimates As Nullable(Of Double)
    Public Property fldPreviousUnapprovedClaims As Nullable(Of Double)
    Public Property fldAdd1Label As String
    Public Property fldAdd1Type As String
    Public Property fldAdd2Label As String
    Public Property fldAdd2Type As String
    Public Property fldAdd3Label As String
    Public Property fldAdd3Type As String
    Public Property fldAdd4Label As String
    Public Property fldAdd4Type As String
    Public Property fldAINUMLabel As String
    Public Property fldCurrentReportingPeriodID As Nullable(Of Integer)
    Public Property fldCurrentValuationGroupID As Nullable(Of Integer)
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldActiveReportToPrint As Nullable(Of Boolean)
    Public Property fldIsTotal As String
    Public Property fldPreviousTotal As Nullable(Of Short)

End Class
