'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSDiscipline
    Public Property fldDisciplineID As Integer
    Public Property fldSystemDefaultDiscipline As Nullable(Of Boolean)
    Public Property fldDisciplineCode As String
    Public Property fldDisciplineDescription As String
    Public Property fldGroupPackageID As Nullable(Of Integer)
    Public Property fldRecordStatus As String
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldProductProjectID As Integer

End Class
