'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSPackage
    Public Property fldPackageID As Integer
    Public Property fldGroupPackageID As Nullable(Of Integer)
    Public Property fldGroupID As Nullable(Of Integer)
    Public Property fldPackageCode As String
    Public Property fldPackageLabel As String
    Public Property fldSequenceNumber As Nullable(Of Integer)
    Public Property fldClientRef As String
    Public Property fldTotalIndicator As String
    Public Property fldDeleted As Nullable(Of Boolean)
    Public Property fldInitialBudget As Nullable(Of Double)
    Public Property fldInitialBudgetLocked As Nullable(Of Boolean)
    Public Property fldTransfers As Nullable(Of Double)
    Public Property fldClientChanges As Nullable(Of Double)
    Public Property fldCurrentBudget As Nullable(Of Double)
    Public Property fldPreviousBudget As Nullable(Of Double)
    Public Property fldAcceptedTenders As Nullable(Of Double)
    Public Property fldOrdersYetToPlace As Nullable(Of Double)
    Public Property fldCostVariations As Nullable(Of Double)
    Public Property fldEstimatedFinalCost As Nullable(Of Double)
    Public Property fldPreviousForecast As Nullable(Of Double)
    Public Property fldGrossValueCertified As Nullable(Of Double)
    Public Property fldContingency As Nullable(Of Double)
    Public Property fldAnticipatedChanges As Nullable(Of Double)
    Public Property fldAdvanceWarnings As Nullable(Of Double)
    Public Property fldDefinedinCatoCP As Nullable(Of Integer)
    Public Property fldPotentialOutturnCosts As Nullable(Of Double)
    Public Property fldAgreedValue As Nullable(Of Double)
    Public Property fldPreviousPotentialOutturnCosts As Nullable(Of Double)
    Public Property fldPreviousAgreedValue As Nullable(Of Double)
    Public Property fldRowOrderId As Nullable(Of Short)
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldRetained As Nullable(Of Double)
    Public Property fldWithheld As Nullable(Of Double)
    Public Property fldLastChangeOrder As Nullable(Of Double)
    Public Property fldProductProjectID As Integer
    Public Property fldSpendToDate As Nullable(Of Double)
    Public Property fldPreviousGrossCertified As Nullable(Of Double)
    Public Property fldPreviousTotalNet As Nullable(Of Double)
    Public Property fldUDBudget1 As Nullable(Of Double)
    Public Property fldUDForecast1 As Nullable(Of Double)
    Public Property fldUDExpenditure1 As Nullable(Of Double)
    Public Property fldUDBudget2 As Nullable(Of Double)
    Public Property fldUDForecast2 As Nullable(Of Double)
    Public Property fldUDExpenditure2 As Nullable(Of Double)
    Public Property fldUDBudget3 As Nullable(Of Double)
    Public Property fldUDForecast3 As Nullable(Of Double)
    Public Property fldUDExpenditure3 As Nullable(Of Double)
    Public Property fldUDBudget4 As Nullable(Of Double)
    Public Property fldUDForecast4 As Nullable(Of Double)
    Public Property fldUDExpenditure4 As Nullable(Of Double)
    Public Property fldContractor As String
    Public Property fldComments As String
    Public Property fldThreshold1 As String
    Public Property fldThreshold2 As String
    Public Property fldPackageLead As String
    Public Property fldName3 As String
    Public Property fldName4 As String
    Public Property fldName5 As String
    Public Property fldRef1 As String
    Public Property fldRef2 As String
    Public Property fldRef3 As String
    Public Property fldPreviousAcceptedTenders As Nullable(Of Double)
    Public Property fldPreviousSpendToDate As Nullable(Of Double)
    Public Property fldName6 As String

End Class
