'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSChangeIndex
    Public Property fldChangeUniqueID As Integer
    Public Property fldGroupPackageID As Nullable(Of Integer)
    Public Property fldChangeIDinGroupPackage As Nullable(Of Integer)
    Public Property fldDescription As String
    Public Property fldFullChangeTypeString As String
    Public Property fldDisciplineID As Nullable(Of Integer)
    Public Property fldStatusID As Nullable(Of Integer)
    Public Property fldDate As String
    Public Property fldPeriodEnteredID As Nullable(Of Integer)
    Public Property fldPeriodAuthorisedID As Nullable(Of Integer)
    Public Property fldAIDate As String
    Public Property fldAINo As String
    Public Property fldInfoFrom As String
    Public Property fldActionComment As String
    Public Property fldSource As String
    Public Property fldFullFromString As String
    Public Property fldFullToString As String
    Public Property fldFullValueAmount As Nullable(Of Double)
    Public Property fldRecordStatus As String
    Public Property fldLocked As Nullable(Of Boolean)
    Public Property fldAdd1Value As String
    Public Property fldAdd2Value As String
    Public Property fldAdd3Value As String
    Public Property fldAdd4Value As String
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldProductProjectID As Integer

End Class
