'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSUserDefineField
    Public Property fldUDFieldID As Integer
    Public Property fldProductProjectID As Nullable(Of Integer)
    Public Property fldUDBUsed1 As Nullable(Of Boolean)
    Public Property fldUDBTitle1 As String
    Public Property fldUDFUsed1 As Nullable(Of Boolean)
    Public Property fldUDFTitle1 As String
    Public Property fldUDEUsed1 As Nullable(Of Boolean)
    Public Property fldUDETitle1 As String
    Public Property fldUDBUsed2 As Nullable(Of Boolean)
    Public Property fldUDBTitle2 As String
    Public Property fldUDFUsed2 As Nullable(Of Boolean)
    Public Property fldUDFTitle2 As String
    Public Property fldUDEUsed2 As Nullable(Of Boolean)
    Public Property fldUDETitle2 As String
    Public Property fldUDBUsed3 As Nullable(Of Boolean)
    Public Property fldUDBTitle3 As String
    Public Property fldUDFUsed3 As Nullable(Of Boolean)
    Public Property fldUDFTitle3 As String
    Public Property fldUDEUsed3 As Nullable(Of Boolean)
    Public Property fldUDETitle3 As String
    Public Property fldUDBUsed4 As Nullable(Of Boolean)
    Public Property fldUDBTitle4 As String
    Public Property fldUDFUsed4 As Nullable(Of Boolean)
    Public Property fldUDFTitle4 As String
    Public Property fldUDEUsed4 As Nullable(Of Boolean)
    Public Property fldUDETitle4 As String

End Class
