'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSChangeDetail
    Public Property fldChangeDetailID As Integer
    Public Property fldChangeIndexID As Nullable(Of Integer)
    Public Property fldChangeTypeID As Nullable(Of Integer)
    Public Property fldChangeFromID As Nullable(Of Integer)
    Public Property fldChangeToID As Nullable(Of Integer)
    Public Property fldChangeDescription As String
    Public Property fldChangeValue As Nullable(Of Double)
    Public Property fldRecordStatus As String
    Public Property fldAgreedValue As Nullable(Of Double)
    Public Property fldAgreed As String
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldChangeOrder As Nullable(Of Double)
    Public Property fldProductProjectID As Integer
    Public Property fldChangeValueA As Nullable(Of Double)
    Public Property fldChangeValueB As Nullable(Of Double)
    Public Property fldChangeValueFlagA As Nullable(Of Boolean)
    Public Property fldChangeValueFlagB As Nullable(Of Boolean)
    Public Property fldComments As String

End Class
