'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCatoCMProject
    Public Property fldCatoCMProjectID As Integer
    Public Property fldProjectID As Nullable(Of Integer)
    Public Property fldVersionID As Nullable(Of Short)
    Public Property fldRevisionID As Nullable(Of Short)
    Public Property fldVersionDescription As String
    Public Property fldRevisionDescription As String
    Public Property fldLatestVersion As Boolean
    Public Property fldLatestRevision As Boolean
    Public Property fldTotalCost As Nullable(Of Double)
    Public Property fldTotalCostRounded As Nullable(Of Double)
    Public Property fldProjectFileName As String
    Public Property fldProjectOffline As Boolean
    Public Property fldProjectOfflineOwner As Nullable(Of Integer)
    Public Property fldPermissionRef As Nullable(Of Short)
    Public Property fldLocked As Nullable(Of Integer)
    Public Property fldLockedBy As String
    Public Property fldStatus As Integer
    Public Property fldUserID As Nullable(Of Integer)
    Public Property fldReadOnly As Boolean
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldMigrated As Nullable(Of Boolean)

End Class
