'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSContract
    Public Property fldContractID As Integer
    Public Property fldProductProjectID As Nullable(Of Integer)
    Public Property fldContractName As String
    Public Property fldContractDescription As String
    Public Property fldRowOrderID As Nullable(Of Short)
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldComments As String
    Public Property fldClassificationID As Nullable(Of Short)
    Public Property fldElementClassName As String

End Class
