'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMColumnOrderDetail
    Public Property fldCMProjectID As Integer
    Public Property fldColumnsOrder As String
    Public Property fldColumnsHidden As String

End Class
