'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMGroupPackageGridHeader
    Public Property fldCMProjectID As Integer
    Public Property fldOption4Installed As String
    Public Property fldGroupPackageCode As String
    Public Property fldGroupPackageLabel As String
    Public Property fldInitialBudget As String
    Public Property fldTransfers As String
    Public Property fldClientChanges As String
    Public Property fldUDBTitle1 As String
    Public Property fldUDBTitle2 As String
    Public Property fldUDBTitle3 As String
    Public Property fldUDBTitle4 As String
    Public Property clcCurrentBudget As String
    Public Property fldAcceptedTenders As String
    Public Property fldOrdersYetToPlace As String
    Public Property fldCostVariations As String
    Public Property fldUDETitle1 As String
    Public Property fldUDETitle2 As String
    Public Property fldUDETitle3 As String
    Public Property fldUDETitle4 As String
    Public Property clcEstimatedFinalCost As String
    Public Property fldContingency As String
    Public Property fldAnticipatedChanges As String
    Public Property fldAdvanceWarnings As String
    Public Property fldUDFTitle1 As String
    Public Property fldUDFTitle2 As String
    Public Property fldUDFTitle3 As String
    Public Property fldUDFTitle4 As String
    Public Property clcPotentialOutturnCost As String
    Public Property fldAgreedValue As String
    Public Property fldGrossValueCertified As String
    Public Property fldSpendToDate As String
    Public Property fldComments As String
    Public Property fldClientRef As String
    Public Property fldRef1 As String
    Public Property fldRef2 As String
    Public Property fldRef3 As String

End Class
