'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSChangeStatu
    Public Property fldStatusID As Integer
    Public Property fldProductProjectID As Nullable(Of Integer)
    Public Property fldSystemDefaultStatus As Nullable(Of Boolean)
    Public Property fldStatusCode As String
    Public Property fldStatusDescription As String
    Public Property fldStatusTrafficLightTypeID As Nullable(Of Integer)
    Public Property fldRecordStatus As String
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldTrafficLightColour As String
    Public Property fldChangeCommentary As String

End Class
