'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCMSValuationGroup
    Public Property fldValuationGroupID As Integer
    Public Property fldValuationDate As Nullable(Of Date)
    Public Property fldGroupPackageID As Nullable(Of Integer)
    Public Property fldDescription As String
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldProductProjectID As Integer

End Class
