'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProject
    Public Property fldProjectID As Integer
    Public Property fldSchemeID As Nullable(Of Integer)
    Public Property fldProjectTitle As String
    Public Property fldProjectNo As String
    Public Property fldProjectDescription As String
    Public Property fldProjectClassDataID As Nullable(Of Integer)
    Public Property fldProjectClass As String
    Public Property fldProjectLocationID As Nullable(Of Integer)
    Public Property fldProjectDate As Nullable(Of Date)
    Public Property fldProjectCurrency As String
    Public Property fldProjectCurrencySymbol As String
    Public Property fldProjectExchangeRate As Nullable(Of Double)
    Public Property fldProjectDeleted As Boolean
    Public Property fldBackup As Nullable(Of Date)
    Public Property fldArchived As Nullable(Of Date)
    Public Property fldSourceID As Nullable(Of Integer)
    Public Property fldProjectDocDir As String
    Public Property fldProjectDocFilter As String
    Public Property fldProjectCreatedBy As String
    Public Property fldProjectCreatedDate As Nullable(Of Date)
    Public Property fldPlannedCompletion As Nullable(Of Date)
    Public Property fldActualCompletion As Nullable(Of Date)
    Public Property fldPrimaveraParentName As String
    Public Property fldPrimaveraName As String
    Public Property fldProjectTaxRate As Nullable(Of Double)
    Public Property fldReportDate As Nullable(Of Date)
    Public Property fldDefaultProjectImageID As Nullable(Of Double)
    Public Property fldDefaultReportImageID As Nullable(Of Double)
    Public Property fldRevisionStageTitle As String
    Public Property fldRevisionStageID As Nullable(Of Short)
    Public Property fldRevisionStageGroupID As Nullable(Of Short)
    Public Property fldClient As String
    Public Property fldClientID As Nullable(Of Short)
    Public Property fldClientGroupID As Nullable(Of Short)
    Public Property fldClientGroup As String
    Public Property fldISCPTemplate As Nullable(Of Boolean)

End Class
