'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPhraseCommentaryData
    Public Property fldPhraseID As Integer
    Public Property fldProductID As Integer
    Public Property fldProductProjectID As Integer
    Public Property fldDescription As String
    Public Property fldPhraseData As String
    Public Property fldPhraseDataRTF As String

End Class
