'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblReportGeneric
    Public Property fldReportGenericGuid As System.Guid
    Public Property fldProductProjectID As Nullable(Of Integer)
    Public Property fldReportFormatID As Nullable(Of Integer)
    Public Property fldReportTitle As String
    Public Property fldReportRTFData As String
    Public Property fldOwnerType As Nullable(Of Integer)

End Class
