'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblUser
    Public Property fldUserID As Integer
    Public Property fldUser As String
    Public Property fldUserName As String
    Public Property fldUserPassword As String
    Public Property fldUserStatus As Boolean
    Public Property fldPermissionRef As Nullable(Of Short)
    Public Property fldSourceID As Nullable(Of Integer)

End Class
