'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblXEvent
    Public Property fldKeepMSSQLHappyID As Integer
    Public Property fldID1 As Nullable(Of Integer)
    Public Property fldEventID As Integer
    Public Property fldEventParams As String

End Class
